### ISSUE TITLE
Chapter 7, question 7-1 confusion

### ISSUE THREAD

**Issue by DalerAsrorov** [PacktPublishing/Mastering-JavaScript-Functional-Programming#1]
Hello, I went over the 7th chapter and there is a question that made me a little confused.
```
7.1. Sum as you will: The following exercise will help you understand some of
the concepts we dealt with in this chapter, even if you solve it without using
any of the functions we looked at. Write a sumMany() function that lets you
sum an indeterminate quantity of numbers, in the following fashion. Note that when
the function is called with no arguments, the sum is returned.
```

```javascript
let result = sumMany((9)(2)(3)(1)(4)(3)());
```
The number `9` is not a function, so the error that is immediately being triggered is:
```
console.log((9)());
               ^

TypeError: 9 is not a function
```
Is there a typo by any chance? I trying different ways to avoid this error, but not sure if I am doing anything wrong.

**Comment by ghost** [comment]
Hi, 

`const sumMany = total => number =>  number === undefined ? total : sumMany(total + number);`

I think this should be the answer.

Explanation : 

`const sumMany` 

defines a function `sumMany()`

`= total => number =>`

defines the arguments of the function `sumMany()`
According to this, the first argument will be `total` and all the next ones will be `number`.

` number === undefined ? total : sumMany(total + number);`

This is a check,

in programming, `?` is a ternary operator. Example, If I say 
`a? b : c`

Then this tells the program that if `a` is true then do `b` else do `c` .

Here it says that if number is undefined then return `total` else add the value of `total` and `number` and return the sum.

so for
`console.log((9)());`

`number === undefined?` will give true and hence return the total.

**Comment by ghost** [comment]
Also it should be 
`sumMany(9)(2)(3)(1)(4)(3)();`

not 
`sumMany((9)(2)(3)(1)(4)(3)());`

Read my above answer for the explanation.

**Comment by DalerAsrorov** [comment]
Hi, thanks for trying to clarify this for me. I believe that it should be:
```javascript
sumMany(9)(2)(3)(1)(4)(3)();
```

The solution that I came up with is recursive, not reliant on the arrow functions.
```javascript
const sumMany = (a) => (b) => {
    if (b === undefined) {
        return a;
    }

    return sumMany(a + b);
};

let result = sumMany(10)(2)(3)(1)(4)(3)();

console.log(result);
```
